database:
  connection:
    host: localhost
    port: 3306
    usr: root
    pwd: 65a1561425f744e2b541303f628963f8
    using: pilipala_fs

  pooling:
    size: 32
    sync: 180

  map:
    meta: container.meta
    record: container.record
    comment: container.comment
    token: auth.token

plugin: ["./plugin/Mailssage", "./plugin/Llink"]

service: ["./serv/Palang", "./serv/Version", "./serv/Shutdown"]

log:
  pilipala.serv.Auth: Information
  pilipala.serv.Palang: Information
  pilipala.serv.Version: Information
  pilipala.serv.Shutdown: Information

auth:
  port: 20222
