database:
  host: localhost
  port: 3306

  user: root
  password: 65a1561425f744e2b541303f628963f8

  poolSize: 32

  dbName: pilipala_fs

  table:
    meta: meta
    record: record
    comment: comment
    token: token

  syncSpan: 180000
plugin: ["./plugins/mailssage", "./plugins/llink"]
auth:
  port: 20222
