database:
  connection:
    host: localhost
    port: 3306
    usr: root
    pwd: 65a1561425f744e2b541303f628963f8
    using: pilipala_fs

  pooling:
    size: 32
    sync: 180

  map:
    meta: container.meta
    record: container.record
    comment: container.comment
    token: auth.token

plugin: ["./plugins/mailssage", "./plugins/llink"]

service: ["palang", "version", "shutdown"]

log: ["pala-std-output", "pala-std-error"]

auth:
  port: 20222
